
https://github.com/keithnull/TeachYourselfCS-CN/blob/master/TeachYourselfCS-CN.md
https://github.com/Clemensss/TeachYourselfCS-PT/blob/master/TeachYourselfCS-PT.md
https://github.com/ilmoi/teachyourselfCS-RU/blob/master/Teach_yourself_cs-2020-RU.md
https://github.com/htdat/TeachYourselfCS-vi/blob/main/README.md
https://github.com/jamesleeat/TeachYourselfCS-ES/blob/main/TeachYourselfCS-ES.md
https://github.com/minnsane/TeachYourselfCS-KR/blob/main/README.md
https://github.com/ralphplumley/TeachYourselfCS-JP/blob/main/%E6%97%A5%E6%9C%AC%E8%AA%9E.md
https://github.com/tolgabp/TeachYourselfCS-TR/blob/main/TeachYourselfCS-TR.md
https://github.com/F4R4N/TeachYourselfCS-FA/blob/main/TeachYourselfCS-FA.md
https://github.com/fabiocicerchia/TeachYourselfCS-IT/blob/main/TeachYourselfCS-IT.md
https://github.com/ChocolateCharlie/TeachYourselfCS-FR/blob/main/TeachYourselfCS-FR.md
https://github.com/zweimach/TeachYourselfCS-ID
https://github.com/ounissi-zakaria/TeachYourselfCS-AR/blob/main/TeachYourselfCS-AR.md
https://github.com/lesfiddler/TeachYourselfCS-UK/blob/master/TeachYourselfCS-UK.md
https://t.co/zZrtSIzhlR
https://twitter.com/BenedictEvans/status/694342874729545729
https://twitter.com/jenna/status/838161631662092289
https://sarabander.github.io/sicp/html/index.xhtml
https://ocw.mit.edu/courses/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video_galleries/video-lectures/
https://archive.org/details/ucberkeley-webcast-PL3E89002AA9B9879E?sort=titleSorter
http://exercism.io
https://composingprograms.com/
http://www.htdp.org/
https://www.reddit.com/r/learnprogramming/wiki/faq#wiki_getting_started
https://sarabander.github.io/sicp/html/index.xhtml
http://csapp.cs.cmu.edu/3e/home.html
http://csapp.cs.cmu.edu/3e/courses.html
http://www.nand2tetris.org
https://www.coursera.org/learn/build-a-computer
https://smile.amazon.com/Computer-Organization-Design-Fifth-Architecture/dp/0124077269
http://inst.eecs.berkeley.edu/~cs61c/sp15/
https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iCl2-D-FS5mk0jFF6cYSJs_
http://csapp.cs.cmu.edu/3e/home.html
https://www.youtube.com/watch?v=rX0ItVEVjHc
https://smile.amazon.com/Algorithm-Design-Manual-Steven-Skiena/dp/1848000693/
https://www3.cs.stonybrook.edu/~skiena/373/videos/
https://www.coursera.org/specializations/algorithms
http://timroughgarden.org/videos.html
http://leetcode.com
https://smile.amazon.com/How-Solve-Mathematical-Princeton-Science/dp/069116407X/
https://smile.amazon.com/Algorithm-Design-Manual-Steven-Skiena/dp/1848000693/
https://smile.amazon.com/How-Solve-Mathematical-Princeton-Science/dp/069116407X/
https://cims.nyu.edu/~regev/teaching/discrete_math_fall_2005/dmbook.pdf
https://courses.csail.mit.edu/6.042/spring17/mcs.pdf
https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/video_galleries/video-lectures/
https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
https://www.amazon.com/Introduction-Linear-Algebra-Gilbert-Strang/dp/0980232775/
https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/
https://www.amazon.com/dp/1118063333/
https://www.amazon.com/dp/013359162X/
http://pages.cs.wisc.edu/~remzi/OSTEP/
https://www.amazon.com/Lions-Commentary-Unix-John/dp/1573980137/
https://www.amazon.com/Design-Implementation-FreeBSD-Operating-System/dp/0321968972/
https://www.amazon.com/Mac-OS-Internals-Systems-Approach/dp/0321278542/
https://www.amazon.com/Linux-Kernel-Development-Robert-Love/dp/0672329468
https://pdos.csail.mit.edu/6.828/2016/xv6.html
http://pages.cs.wisc.edu/~remzi/OSTEP/lab-projects-xv6.pdf
http://pages.cs.wisc.edu/~remzi/OSTEP/
https://smile.amazon.com/Computer-Networking-Top-Down-Approach-7th/dp/0133594149/
http://www-net.cs.umass.edu/wireshark-labs/
https://www.youtube.com/playlist?list=PLoCMsyE1cvdWKsLVyf6cPwCLDIZnOj0NS
https://smile.amazon.com/Computer-Networking-Top-Down-Approach-7th/dp/0133594149/
https://www.youtube.com/user/CS186Berkeley/videos
http://db.cs.berkeley.edu/papers/fntdb07-architecture.pdf
http://www.redbook.io/
https://smile.amazon.com/Database-Management-Systems-Raghu-Ramakrishnan/dp/0072465638/
https://www.amazon.com/Transaction-Processing-Concepts-Techniques-Management/dp/1558601902
https://www.amazon.com/Data-Reality-Perspective-Perceiving-Information/dp/1935504215
http://www.redbook.io/
https://www.amazon.com/Data-Reality-Perspective-Perceiving-Information/dp/1935504215
https://craftinginterpreters.com/contents.html
https://smile.amazon.com/Compilers-Principles-Techniques-Tools-2nd/dp/0321486811
https://www.edx.org/course/compilers
https://smile.amazon.com/Compilers-Principles-Techniques-Tools-2nd/dp/0321486811
https://smile.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable-ebook/dp/B06XPJML5D/
https://www.distributed-systems.net/index.php/books/ds3/
https://www.youtube.com/watch?v=cQP8WApzIQQ&list=PLrw6a1wE39_tb2fErI4-WkMbsvGQk9_UB
https://pdos.csail.mit.edu/6.824/schedule.html
http://dsrg.pdos.csail.mit.edu/papers/
http://paperswelove.org/
https://smile.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable-ebook/dp/B06XPJML5D/
http://ai.berkeley.edu/
http://inst.eecs.berkeley.edu/~cs184/fa12/onlinelectures.html
https://www.amazon.com/Computer-Graphics-Principles-Practice-3rd/dp/0321399528
https://github.com/open-source-society/computer-science
https://twitter.com/oznova_
https://twitter.com/quackingduck
https://bradfieldcs.com/csi/
https://ozwrites.com/masters/
